### PR TITLE
Feature rope

### PR DESCRIPTION
**Pull request by NicolaeChristof**
Hey guys so I just finished the core mechanic of our game, the Rope Swing. Hope you guys enjoy.

How to test:
1. move around the scene, you should see pictures of nathan appear, these represent the grab points
2. use left mouse click to attach yourself to a nearby grab point
3. use arrow keys while attached to move around
4. left click again to detach from grab point
5. click and hold left click while near a grab point to swing, releasing left click will detach from grab point
Try to make it to the top of the scene

### CODE REVIEW

**Review by Lqn8r — APPROVED** [review]
Looks good, the rope detection is a bit clunky but swinging from anchor to anchor works fairly well.

**Comment by NicolaeChristof** [comment]
I plan to work on it more going forward so hopefully I'll be able to tighten up the detection. Our player will also be moving down not up so maybe that will be better

**Comment by Lqn8r** [comment]
Yeah there's some weird interactions where the rope gets longer the more you hold onto it and it sometimes clips through the walls to attach to anchors.

**Comment by NicolaeChristof** [comment]
Yeah that has to do with the raycast. I'm not sure how (or if I should) tell it not to. And the reason the rope gets longer over time has to do with the physics of the interaction. The rope doesn't actually do anything, it's just visual. There is some math going on in the background that hold the player up and its just adding a force in the upward direction to keep the player floating

**Review by AadamM — APPROVED** [review]
It's looking great and it's really fun trying to get to the top of the rope! I agree that the rope sometimes gets too long and makes me skid, but that won't be much of an issue when the main goal is to lower yourself. As it stands the rope mechanic is adding a lot to the core game play, so I approve!

**Comment by NicolaeChristof** [comment]
Thanks! I worked really hard on that mechanic so I'm really glad to hear you enjoyed it. I had a friend playtest it today and they enjoyed it as well

**Pull request merged**
