### PR TITLE
Feature Lighting + Basic Camp

### PR DESCRIPTION
**Pull request by AadamM**
This PR is mostly focused on lighting. I've attached a torch to the character that lets them see things in their immediate vicinity. I've also included some of the glowing mushrooms that we've talked about. The scene is generally darker, but it does have some ambient lighting from the skylight (whose intensity can be raised or lowered).

Additionally, I've added the ability to place the camp down. If you hit the P button when near a pole (there's only one currently in the stage. It's to the right of the entrance to the cave, on the surface) it'll spawn a camp (which provides a bit of lighting as well).

How to test:
Make sure that the scene isn't too dark and that the scene is bright enough that you're able to make it to the goal. Additionally, make sure that the camp spawns when you hit the P near a pole. It doesn't currently let you respawn at it as I haven't merged in the health system yet.

Known bugs:
If you're right near the pole when you hit P, the tent will spawn around you.
Also, there seem to be 2 player blueprints (one in the SideScrollerCPP/Blueprints folder and one in the Assets/Blueprints folder). I'm assuming we're using the one in the assets folder, but I left the one in the SideScrollerCPP folder to make sure there aren't any compatibility issues.

### CODE REVIEW

**Comment by NicolaeChristof** [comment]
I took a look at the two player blueprints and the one we should be using is the one under Content > Blueprints. You can remove the other one along with the SideScrollerCPP folder as I don't believe it is being used for anything and I dont want us to get confused.

**Review by NicolaeChristof — CHANGES_REQUESTED** [review]
Hey so this looks really great and it definitely adds a lot to the game. A couple things to note.
1. I couldn't find the campspawn pole you mentioned so I wasn't able to test that.
2. The second player bp in the sidescroller folder should be deleted since it is not the one we are using. (you can delete the folder while you are at it)
3. There seems to be a bug with the swinging which causes me to fly off into space whenever I attempt to swing. That might be a problem with something I did so I will take a look at it after we merge this.

Other than that excellent work!

**Comment by AadamM** [comment]
Good catch. I changed the look of the flagpole so that it's easier to see. I deleted the SideScrollerCPP folder, and also merged in the fall_damage branch. I encountered the rope issue that you were mentioning, but I can't figure out to fix it (I removed collision on the torch because I thought that was doing it, but it didn't make a difference since it didn't have a collision box in the first place)

**Review by NicolaeChristof — APPROVED** [review]

**Review by Lqn8r — APPROVED** [review]
Looks good.

**Pull request merged**
