### PR TITLE
Feature fall damage

### PR DESCRIPTION
**Pull request by NicolaeChristof**
I'm laughing too hard at this. Enjoy. Ok so I've implemented fall damage and a death state.

To Test:
1. go jump off the biggest ledge you can find
2. watch that health bar drop
3. repeat steps 1 and 2 until death.
4. enjoy the ragdoll physics

No known bugs

### CODE REVIEW

**Review by Lqn8r — APPROVED** [review]
Looks good.

**Review by AadamM — COMMENTED** [review]
I love the ragdoll impact and the new textures! I ran into a glitch where if I fell from the top without hitting any of the other platforms, I'd drop to 0 health when I hit the ground but wouldn't ragdoll nor die.

**Comment by NicolaeChristof** [comment]
Ill take a look at that

**Comment by NicolaeChristof** [comment]
I fixed that bug you found. I was checking if health was < 0 instead of <= 0 and I was setting an instadeath (if you fall from a certain height its death no matter what) to 0.

**Review by AadamM — APPROVED** [review]
Just took a look at it and the glitch is fixed! Approved!

**Pull request merged**
