### PR TITLE
Feature fall stone

### PR DESCRIPTION
**Pull request by NicolaeChristof**
This ones a fun one. Player can now drop depth gauges to determine if a fall is survivable.

To Test:
1. approach a ledge and press F, the player will spawn a depth gauge
2. once the gauge hits the ground it will display true or false in the top left (right under the health bar) whether or not the fall is survivable.

Known Bugs:
no known bugs

Notes:
I plan to make some kind of effect (sound plus visual) in the future but for now this is the functionality

### CODE REVIEW

**Review by AadamM — COMMENTED** [review]
It works great and is really fun to drop (espeically when swinging). I ran into a issue where if I got my health down low enough, the ball would say a small fall was survivable yet I'd still die on impact since my health was low (IE: I'm not sure if the ball takes the player's current health into consideration)

**Comment by NicolaeChristof** [comment]
The gauge takes player health when the gauge is spawned. I think the gauge might have a slightly different mass or something like that which causes subtle variations. I did notice the player falls faster than the gauge, I think

**Review by Lqn8r — APPROVED** [review]
Looks good.

**Review by AadamM — APPROVED** [review]
Feels great! Approved!

**Pull request merged**
